# Generated by Django 4.2.6 on 2023-10-18 17:28
import json
import os
from pathlib import Path

from django.db import migrations


def load_data(apps, schema_editor):
    """Загрузка прав для группы авторизованных через google account"""
    Group = apps.get_model('auth', 'group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    if schema_editor.connection.alias != 'default':
        return

    new_group, created = Group.objects.get_or_create(name='Google_authorization')
    if not created:
        return

    current_path = Path(os.path.dirname(os.path.realpath(__file__)))
    json_path = os.path.join(current_path, '../fixtures/permissions.json')

    with open(json_path, encoding='utf-8') as f:
        permissions = json.load(f)

    list_of_permissions = []
    for item in permissions:
        model = apps.get_model('mailing', item.get('model'))
        content_type = ContentType.objects.get_for_model(model)
        permission = Permission.objects.create(
            codename=item.get('codename'),
            name=item.get('name'),
            content_type=content_type,
        )
        list_of_permissions.append(permission)

    new_group.permissions.add(*list_of_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=load_data, reverse_code=lambda a, s: 1),
    ]
